<?php
$title = 'Log in';
$this->headTitle($title);
$this->form->prepare()
?>

<h1><?php echo $this->escapeHtml($title) ?></h1>
<div class="row">
    <div class="col-sm-12">

        <?php echo $this->form()->openTag($form) ?><br>
        <div class="form-group">
            <?php echo $this->formRow($form->get('username')) ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('password')) ?>
        </div>
        <?php echo $this->formSubmit($form->get('submit')) ?>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>
