<?php
 $title = 'Log in';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 //$form->setAttribute('action', $this->url('backupdb/dump', array('action' => 'login')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('username'));
 echo $this->formRow($form->get('password'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();