<!-- here we have pure html-->
<?php
 $title = 'Backup Control Panel';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
<pre>
    <!-- here we can represent data from controllers action-->
    <?php //print_r($this->something); ?>
</pre>
<?php 
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('fileupload'));
echo $this->formSubmit($form->get('uploadsubmit'));
echo '<br>The file will be added to the selection list with the name: '
. 'LISBACKUP_upload_[DATE]_[TIME]';
echo $this->form()->closeTag();

echo $this->form()->openTag($form);
echo '<br>';
echo $this->formRow($form->get('fileselect'));
echo '<br>';
echo $this->formSubmit($form->get('downloadsubmit'));
echo '<br>';
echo $this->formRow($form->get('pushcheckbox'));
echo '<br>';
echo $this->formSubmit($form->get('pushsubmit'));
echo $this->form()->closeTag();

echo $this->form()->openTag($form);
echo $this->formSubmit($form->get('logoutsubmit'));
echo $this->form()->closeTag();