<!-- here we have pure html-->
<?php
$title = 'Backup Control Panel';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<?php
if ($this->showPanelForm) {
    $this->form->prepare();
    echo $this->form()->openTag($form);
    
    echo '<div class="form-group">';        
    echo '<br>';
    echo '<b>New Backup</b>';
    echo '<br>';
    echo $this->formSubmit($form->get('createsubmit'));
    echo '</div>';
    
    
    echo '<br>';
    echo 'This creates a backup of the current database on the server with the name: '
    . 'LISBACKUP_server_[DATE]_[TIME]';
    echo '<br><br>';
    echo $this->form()->closeTag();

    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('fileupload'));
    echo $this->formSubmit($form->get('uploadsubmit'));
    echo '<br>The file will be added to the selection list with the name: '
    . 'LISBACKUP_upload_[DATE]_[TIME]';
    echo $this->form()->closeTag();

    echo $this->form()->openTag($form);
    echo '<br>';
    echo '<b>Server file controls</b>';
    echo '<br>';
    echo $this->formRow($form->get('fileselect'));
    echo '<br>';
    echo 'This interface does not allow deleting backups from the server.';
    echo '<br>';
    echo 'If the list is too long or cluttered, access the server directly via ssh to delete or relocate unnecessary backups.';
    echo '<br>';
    echo '<br>';
    echo $this->formSubmit($form->get('downloadsubmit'));
    echo '<br>';
    echo 'This downloads the selected backup from the server';
    echo '<br>';
    echo $this->formSubmit($form->get('pushsubmit'));
    echo '<br>';
    echo 'Warning: This overwrites the existing database with the selected backup. '
    . 'The operation is not reversible.';
    echo '<br>';
    echo "Check the box below if you're sure you have selected the correct backup.";
    echo '<br>';
    echo $this->formRow($form->get('pushcheckbox'));
    echo $this->form()->closeTag();

    echo $this->form()->openTag($form);
    echo '<br>';
    echo $this->formSubmit($form->get('logoutsubmit'));
    echo '<br>';
    echo 'Safely logs out of the control panel.';
    echo $this->form()->closeTag();
} else {
    if ($this->actionSuccess) {
        ?>

        <div class="alert alert-success">
            <strong>:)</strong> <?php echo $this->message?>
        </div>

    <?php } else { ?>

        <div class="alert alert-danger">
            <strong>:(</strong> <?php echo $this->message?>
        </div>

    <?php
    }
}
?>
