<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Pärnu STK LIS')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('zassets/css/style.css'))
            ->prependStylesheet($this->basePath('zassets/css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('zassets/css/bootstrap.min.css')) ?>
        <style>
            body {
                padding: 0px;
            }
        </style>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('zassets/js/bootstrap.min.js'))
            ->prependFile($this->basePath('zassets/js/jquery.min.js'))
            ->prependFile($this->basePath('zassets/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('zassets/js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <div class="navbar-header navbar-inverse">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/#"><img src="<?php echo $this->basePath('zassets/img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp; LIS</a>
    </div>
    <div class="collapse navbar-collapse navbar-inverse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><a href="/app/administrator/">Administrator</a></li>
            <li><a href="/app/student/">Student</a></li>
            <li><a href="/app/teacher/">Teacher</a></li>
            <li><a href="/apidocs/">Documentation</a></li>
        </ul>
    </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>


            <footer>
                Application Layout | <a href="https://github.com/parnustk/lisbackend">GitHub repository</a>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
