<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                 <h3 class="panel-title">Lorem ipsum</h3>
            </div>
            <div class="panel-body">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sapien sapien, molestie non leo sit amet, ornare luctus arcu. Suspendisse vitae dui ut leo dapibus fermentum vitae in erat. Vestibulum euismod, est non consectetur volutpat, mauris augue ultricies mi, non dignissim neque metus vel urna.</p>
                <p><a class="btn btn-success pull-right" href="/app/student">Student &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Lorem ipsum</h3>
            </div>
            <div class="panel-body">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis a leo vel metus suscipit porttitor finibus et est. Vestibulum euismod, est non consectetur volutpat, mauris augue ultricies mi, non dignissim neque metus vel urna.</p>
                <p><a class="btn btn-success pull-right" href="/app/teacher">Teacher &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Lorem ipsum</h3>
            </div>
            <div class="panel-body">
                <p>Duis a leo vel metus suscipit porttitor finibus et est. In sapien sapien, molestie non leo sit amet, ornare luctus arcu. Suspendisse vitae dui ut leo dapibus fermentum vitae in erat. Vestibulum euismod, est non consectetur volutpat, mauris augue ultricies mi, non dignissim neque metus vel urna.</p>
                <p><a class="btn btn-success pull-right" href="/app/administrator">Administrator &raquo;</a></p>
            </div>
        </div>
    </div>
</div>