<h2></h2>
<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                 <h3 class="panel-title">Sisene õpilasena</h3>
            </div>
            <div class="panel-body">
                <p>Näed enda hindeid, puudumisi ja tunniplaani. Mobiilisõbralik.</p>
                <p><a class="btn btn-success pull-right" href="/app/student">Sisene &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Sisene õpetajana</h3>
            </div>
            <div class="panel-body">
                <p>Päevikute haldamine.</p>
                <p><a class="btn btn-success pull-right" href="/app/teacher">Sisene &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Sisene administraatorina</h3>
            </div>
            <div class="panel-body">
                <p>Süsteemi, ligipääsude, õppekavade ja isikute haldamine.</p>
                <p><a class="btn btn-success pull-right" href="/app/administrator">Sisene &raquo;</a></p>
            </div>
        </div>
    </div>
</div>