<?php

namespace Core\Entity\Repository;

/**
 * AdministratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministratorRepository extends \Doctrine\ORM\EntityRepository
{
}
