<?php

namespace Core\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdministratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministratorRepository extends EntityRepository implements CRUD
{

    /**
     * {@inheritDoc}
     */
    public function GetList($params = null, $extra = null)
    {
        
    }

    /**
     * {@inheritDoc}
     */
    public function Get($id, $returnPartial = false, $extra = null)
    {
        
    }

    /**
     * {@inheritDoc}
     */
    public function Create($data, $returnPartial = false, $extra = null)
    {
        
    }

    /**
     * {@inheritDoc}
     */
    public function Update($id, $data, $returnPartial = false, $extra = null)
    {
        
    }

    /**
     * {@inheritDoc}
     */
    public function Delete($id, $extra = null)
    {
        
    }

}
