<?php

namespace Core\Entity\Repository;

/**
 * GradeSubjectRoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeSubjectRoundRepository extends \Doctrine\ORM\EntityRepository
{
}
