<?php

namespace Core\Entity\Repository;

/**
 * GradeChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeChoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
