<?php

namespace Core\Entity\Repository;

/**
 * GradeIndependentWorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeIndependentWorkRepository extends \Doctrine\ORM\EntityRepository
{
}
