<?php

namespace Core\Entity\Repository;

/**
 * GradeModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeModuleRepository extends \Doctrine\ORM\EntityRepository
{
}
