<?php

namespace Core\Entity\Repository;

/**
 * IndependentWorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndependentWorkRepository extends \Doctrine\ORM\EntityRepository
{
}
