<?php

namespace Core\Entity\Repository;

/**
 * LisUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LisUserRepository extends \Doctrine\ORM\EntityRepository
{
}
