<?php

namespace Core\Entity\Repository;

use Core\Entity\Rooms;
use Doctrine\ORM\EntityRepository;
use DoctrineORMModule\Paginator\Adapter\DoctrinePaginator;
use Doctrine\ORM\Tools\Pagination\Paginator as ORMPaginator;
use Zend\Paginator\Paginator;
use Exception;
use Zend\Json\Json;
use Doctrine\ORM\Query;

/**
 * RoomsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomsRepository extends EntityRepository implements CRUD
{

    public function Create($data, $returnPartial = false, $extra = null)
    {
        
        $entity = new Rooms($this->getEntityManager());
        $entity->hydrate($data);
        
        if (!$entity->validate()) {
            throw new Exception(Json::encode($entity->getMessages(), true));
        }

        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush($entity);

        if ($returnPartial) {

            $dql = "
                    SELECT 
                        partial ro.{id,name}
                    FROM Core\Entity\Rooms ro
                    WHERE ro.id = " . $entity->getId() . "
                ";

            $q = $this->getEntityManager()->createQuery($dql); //print_r($q->getSQL());
            $r = $q->getSingleResult(Query::HYDRATE_ARRAY);
            
            return $r;
        }

        return $entity;
    }

    public function Delete($id, $extra = null)
    {
        $this->getEntityManager()->remove($this->find($id));
        $this->getEntityManager()->flush();
        return $id;
    }

    public function Get($id, $returnPartial = false, $extra = null)
    {
        if ($returnPartial) {
            $dql = "
                    SELECT 
                        partial ro.{id,name}
                    FROM Core\Entity\Rooms ro
                    WHERE ro.id = :id";

            $q = $this->getEntityManager()->createQuery($dql); //print_r($q->getSQL());
            $q->setParameter("id", $id);

            return $q->getSingleResult(Query::HYDRATE_ARRAY);
        }
        return $this->find($id);
    }

    public function GetList($params = null, $extra = null)
    {
        if ($params) {
            //todo if neccessary
        }
        
        $dql = "SELECT 
                    partial ro.{
                        id,
                        name
                    }
                FROM Core\Entity\Rooms ro
                WHERE ro.trashed IS NULL";

        return new Paginator(
                new DoctrinePaginator(
                new ORMPaginator(
                $this->getEntityManager()
                        ->createQuery($dql)
                        ->setHydrationMode(Query::HYDRATE_ARRAY)
                )
                )
        );
    }

    public function Update($id, $data, $returnPartial = false, $extra = null)
    {
        $entity = $this->find($id);
        $entity->setEntityManager($this->getEntityManager());
        $entity->hydrate($data);

        if (!$entity->validate()) {
            throw new Exception(Json::encode($entity->getMessages(), true));
        }

        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush($entity);

        if ($returnPartial) {
            $dql = "
                    SELECT 
                        partial ro.{id,name}
                    FROM Core\Entity\Rooms ro
                    WHERE ro.id = :id";
            
            $q = $this->getEntityManager()->createQuery($dql); //print_r($q->getSQL());
            $q->setParameter("id", $id);
            
            $r = $q->getSingleResult(Query::HYDRATE_ARRAY);
            return $r;
        }
        return $entity;
    } 

}
