<?php

namespace Core\Entity\Repository;

/**
 * SubjectRoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRoundRepository extends \Doctrine\ORM\EntityRepository
{
}
